import React from 'react';
import Link from 'next/link';
import { Shield, AlertTriangle, FileText, ArrowLeft, CheckCircle2 } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-8">
      <Link href="/" className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-400 hover:text-indigo-400 transition-colors">
        <ArrowLeft className="w-4 h-4" />
        Back to Home
      </Link>

      <div className="border-b border-slate-800 pb-5 space-y-2">
        <div className="inline-flex items-center space-x-2 px-3 py-1 bg-amber-500/10 border border-amber-500/20 rounded-full text-amber-400 text-xs font-semibold">
          <AlertTriangle className="w-3.5 h-3.5" />
          <span>Product Safety &amp; Service Boundaries</span>
        </div>
        <h1 className="text-3xl font-extrabold text-slate-100">LegalLens AI — Terms of Service</h1>
        <p className="text-slate-400 text-sm">
          Last Updated: September 2026 | Non-Legal Advice &amp; Navigation Boundaries
        </p>
      </div>

      <div className="space-y-6 text-slate-300 text-sm leading-relaxed">
        <section className="bg-slate-900 p-6 rounded-2xl border border-slate-800 space-y-3">
          <h2 className="text-base font-bold text-slate-100 flex items-center gap-2">
            <Shield className="w-4 h-4 text-indigo-400" />
            1. Information &amp; Navigation Assistance (Not Legal Advice)
          </h2>
          <p>
            LegalLens AI provides AI-assisted document navigation, plain-language summaries, risk mapping, and preparation questions. LegalLens AI does NOT provide professional legal advice, legal representation, or court predictions.
          </p>
          <div className="p-3.5 bg-amber-950/20 border border-amber-500/30 rounded-xl text-amber-300 text-xs font-medium">
            <strong>Important Boundary:</strong> Always consult a qualified attorney in your local jurisdiction for specific legal counsel before making binding decisions.
          </div>
        </section>

        <section className="bg-slate-900 p-6 rounded-2xl border border-slate-800 space-y-3">
          <h2 className="text-base font-bold text-slate-100 flex items-center gap-2">
            <FileText className="w-4 h-4 text-indigo-400" />
            2. User Responsibilities &amp; Document Ownership
          </h2>
          <p>
            You warrant that you own or have lawful authorization to upload and analyze any documents submitted to LegalLens AI. You must not upload unlawful or malicious code.
          </p>
        </section>

        <section className="bg-slate-900 p-6 rounded-2xl border border-slate-800 space-y-3">
          <h2 className="text-base font-bold text-slate-100 flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-indigo-400" />
            3. Grounding &amp; Evidence Standards
          </h2>
          <p>
            All findings generated by LegalLens AI carry line-level source references traceable to the source document text.
          </p>
        </section>
      </div>
    </div>
  );
}
